{% set name = "subprocess-tee" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/subprocess-tee-{{ version }}.tar.gz
  sha256: 673a832a2a0a1e635ecf1b68673d16e838e945aa953af04aaf8a22b1e9f92ae8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - setuptools_scm_git_archive >=1.0
  run:
    - python >=3.6

test:
  imports:
    - subprocess_tee
    - subprocess_tee.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pycontribs/subprocess-tee
  summary: subprocess-tee
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
